// Generated by gencpp from file pick_place_msgs/PickStepResponse.msg
// DO NOT EDIT!


#ifndef PICK_PLACE_MSGS_MESSAGE_PICKSTEPRESPONSE_H
#define PICK_PLACE_MSGS_MESSAGE_PICKSTEPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace pick_place_msgs
{
template <class ContainerAllocator>
struct PickStepResponse_
{
  typedef PickStepResponse_<ContainerAllocator> Type;

  PickStepResponse_()
    : success(false)
    , message()
    , pose()  {
    }
  PickStepResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PickStepResponse_

typedef ::pick_place_msgs::PickStepResponse_<std::allocator<void> > PickStepResponse;

typedef boost::shared_ptr< ::pick_place_msgs::PickStepResponse > PickStepResponsePtr;
typedef boost::shared_ptr< ::pick_place_msgs::PickStepResponse const> PickStepResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_place_msgs::PickStepResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_place_msgs::PickStepResponse_<ContainerAllocator1> & lhs, const ::pick_place_msgs::PickStepResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_place_msgs::PickStepResponse_<ContainerAllocator1> & lhs, const ::pick_place_msgs::PickStepResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_place_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b6397e59d82097d3d62422ba9e3c882";
  }

  static const char* value(const ::pick_place_msgs::PickStepResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b6397e59d82097dULL;
  static const uint64_t static_value2 = 0x3d62422ba9e3c882ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_place_msgs/PickStepResponse";
  }

  static const char* value(const ::pick_place_msgs::PickStepResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# -------- Response -------\n"
"bool success\n"
"string message\n"
"geometry_msgs/Pose pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pick_place_msgs::PickStepResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickStepResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_place_msgs::PickStepResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_place_msgs::PickStepResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_PLACE_MSGS_MESSAGE_PICKSTEPRESPONSE_H
